language: go
sudo: false

go:
  - 1.10.x
  - tip

build_matrix:
  allow_failures:
    - tip

before_install:
  - go get -t -v ./...

script:
  - ./test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)

